### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#103]
I see with some regret that there doesn't seem to be many commits / updates to this project recently. 

May I ask if the project is dead / deprecated / mothballed ?

If so, does anyone have a recommendation for another similar project ?

**Comment by chiefy** [comment]
It's not quite dead, but I am just a guy with a family and a day job, so I have very little time to commit to it. I have been trying to set aside some time to clean things up a bit but haven't gotten there yet. 

I am more than happy to accept PRs etc.

**Comment by jmls** [comment]
@chiefy don't get me wrong man - I also have a day job and family (5 kids!) and very little time. I understand where you are coming from. 

I'll see if I can do anything rather than adopt another lib

**Comment by chiefy** [comment]
@jmls no worries, just not a ton of time right now to devote.

**Comment by chiefy** [comment]
@jmls I've marked this project dead in the README. I just don't have the time to get it back to where it should be at this point. Sorry. Let me know if you want to take it.
