### ISSUE TITLE
Feature: Enable support for `auth/ldap` Endpoints

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#18]
Implement, test, and document `auth/ldap` Endpoints

**Comment by kenjones-cisco** [comment]
Online LDAP test server
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

(same one used by Vault team to test their backend)

**Comment by kenjones-cisco** [comment]
With a planned rewrite of the LDAP backend within Vault (https://github.com/hashicorp/vault/issues/546), this can be deferred until that is closer.

hashicorp/vault#546

**Comment by jmls** [comment]
seeing as this has all been done, is it possible to get ldap supported ?
