### ISSUE TITLE
Add more client-related config settings

### ISSUE THREAD

**Issue by chiefy** [chiefy/vaulted#2]
Try to use the [Ruby-client](https://github.com/hashicorp/vault-ruby) as an example and create more configs around using this library as a client. 
ex.
- token
- ssl pem
- ssl verify
- timeout

**Comment by kenjones-cisco** [comment]
### From Vault Ruby

| Vaulted Enabled | Attribute | Environment Variable | Default Value |
| --- | --- | --- | --- |
| [x] | address | VAULT_ADDR | https://127.0.0.1:8200 |
| [x] | token | VAULT_TOKEN | nil |
| [ ] | open_timeout | VAULT_OPEN_TIMEOUT | nil |
| [x] | proxy_address | VAULT_PROXY_ADDRESS | nil |
| [x] | proxy_password | VAULT_PROXY_PASSWORD | nil |
| [x] | proxy_port | VAULT_PROXY_PORT | nil |
| [x] | proxy_username | VAULT_PROXY_USERNAME | nil |
| [ ] | read_timeout | VAULT_READ_TIMEOUT | nil |
| [x] | ssl_ciphers | VAULT_SSL_CIPHERS | TLSv1.2 |
| [x] | ssl_pem_file | VAULT_SSL_CERT | nil |
| [x] | ssl_pem_passphrase | VAULT_SSL_CERT_PASSPHRASE | nil |
| [x] | ssl_ca_cert | VAULT_CACERT | nil |
| [ ] | ssl_ca_path | VAULT_CAPATH | nil |
| [x] | ssl_verify | VAULT_SSL_VERIFY | nil |
| [ ] | ssl_timeout | VAULT_SSL_TIMEOUT | nil |
| [x] | timeout | VAULT_TIMEOUT | nil |

### Enabled in Vaulted

| Attribute | Environment Variable | Default Value | Ruby Attribute |
| --- | --- | --- | --- |
| vault_host | VAULT_HOST | 127.0.0.1 | address |
| vault_port | VAULT_PORT | 8200 | address |
| vault_ssl | VAULT_SSL | 1 (enabled) | address |
| vault_token | vault_token | null | token |
| ssl_ciphers | VAULT_SSL_CIPHERS | TLSv1.2 | ssl_ciphers |
| ssl_pem_file | VAULT_SSL_CERT | null | ssl_pem_file |
| ssl_pem_passphrase | VAULT_SSL_CERT_PASSPHRASE | null | ssl_pem_passphrase |
| ssl_ca_cert | VAULT_CACERT | null | ssl_ca_cert |
| ssl_verify | VAULT_SSL_VERIFY | true | ssl_verify |
| timeout | VAULT_TIMEOUT | null | timeout |
| proxy_address | VAULT_PROXY_ADDRESS | null | proxy_address |
| proxy_password | VAULT_PROXY_PASSWORD | null | proxy_password |
| proxy_port | VAULT_PROXY_PORT | null | proxy_port |
| proxy_username | VAULT_PROXY_USERNAME | null | proxy_username |

### Not supported by Vaulted

| Attribute | Environment Variable | Reason |
| --- | --- | --- |
| open_timeout | VAULT_OPEN_TIMEOUT | Not supported by request library |
| read_timeout | VAULT_READ_TIMEOUT | Not supported by request library |
| ssl_timeout | VAULT_SSL_TIMEOUT | Not supported by request library |
| ssl_ca_path | VAULT_CAPATH | Not supported by request library |

**Comment by kenjones-cisco** [comment]
Configuration options added via #36, previous comment provides additional details.

Because `request` expects a cert to be separate from the key also includes `ssl_cert_file` with env `VAULT_SSL_CERT`
