### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by chiefy** [chiefy/vaulted#35]
The current `README.md` is somewhat out-of-date / misleading. Need to add some bettter docs.

**Comment by kenjones-cisco** [comment]
Badges (http://shields.io/)
- [ ] NPM
- [x] Travis Build*
- [x] Coveralls*

*dependent on #12

**Comment by kenjones-cisco** [comment]
- Added documentation for all APIs.
- Added documentation for configuration options and how to configure Vaulted.
- Added documentation for how to get started with New or Existing Vault.
- Updated README
