### ISSUE TITLE
get policy details

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#45]
In the vault documentation, this is not documented , but you can do a GET to sys/policy/:id and get the details back of the policy (rules etc)

Is this possible with vaulted ?

**Comment by kenjones-cisco** [comment]
Yes, the API documentation for that Vaulted API is here:
https://github.com/chiefy/vaulted/blob/master/docs/policy.md#module_policy..getPolicies

**Comment by kenjones-cisco** [comment]
The GET `sys/policy/:id` was not documented as such within Vault, but after trying it out it does work so I have implemented support for it.

**Comment by jmls** [comment]
cheers! you da man.

**Comment by kenjones-cisco** [comment]
Resolved via commit a5e9468a1970a0b67d9b7e1b18063fbdb9b73882
