### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#49]
- [x] Update version in package.json from `2.0.0` to `2.1.1`
- [x] Tag project with tag `v2.1.0`
- [x] Create Github Release for tag `v2.1.0`
- [x] Update CHANGELOG.md with version, date, and link to Github Release.
- [x] Publish `v2.1.0` to NPM

**Comment by jmls** [comment]
/me waits with baited breath ;) thanks for this !

**Comment by chiefy** [comment]
Just published to npm, thanks guys!
