### ISSUE TITLE
feature request : convenience remove leading /

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#52]
It would be "nice" and helpful for the library to remove any leading / from an id for secret / cubbyhole reading & writing.

I've just spent 30 mins trying to figure out why I'm getting an error when trying this code

``` javascript
vault.write({
           id: '/my/data',
           body: {
                authentication: {}
           }
       });
```

it was only when i really looked at the uri did I see 

```
uri: 'http://myserver:8200/v1/secret//my/data'
```

I know, I know. I should be more careful. But it would be _really_ nice for the lib to protect me from such dumbass things ;)

**Comment by kenjones-cisco** [comment]
Resolved with commit 29bccde807a4042bf64fc665d8486209cfd437c4
Should be released as part of v2.2
