### ISSUE TITLE
error writing to cubbyhole

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#53]
I am getting a 400 error when trying to write some data to a cubbyhole. However, I think that it may be a bug in the vault application itself

The error is

```
 error: { errors: [ 'Failed to parse JSON input: json: cannot unmarshal string into Go value of type map[string]interface {}' ] },
```

where the body is a signed jwt compacted token

**Comment by kenjones-cisco** [comment]
Are you using `{key: value}`? The expected input based on Vaults documentation is a key/value.

**Comment by jmls** [comment]
no I wasn't _blushes_
