### ISSUE TITLE
revokeLeasePrefix and revokeLease

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#60]
from what I can see in the docs there is no difference between the two methods. the description for **revokeLeasePrefix** states _Revoke the lease on all secrets under the specified prefix immediately_ 

yet there are no documented options for specifying the prefix ...

**Comment by kenjones-cisco** [comment]
`revokeLease` expects a `lease_id` where as `revokeLeasePrefix` is looking for a secret path prefix.

Docs updated with commit 6151cde993bc7dcf9abf4bf65f88ee3357efddc5
