### ISSUE TITLE
Feature: Support audit-hash API

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#68]
- [x] POST `/sys/audit-hash/<name>`

**Comment by chiefy** [comment]
@kenjones-cisco  can you do a code-review?
#87

**Comment by kenjones-cisco** [comment]
From a code perspective it looks good. Just need some test cases.

**Comment by chiefy** [comment]
@kenjones-cisco forgot to commit my tests, d'oh. Should be in there now.
