### ISSUE TITLE
token not returned on init()

### ISSUE THREAD

**Issue by jmls** [chiefy/vaulted#69]
The results from this piece of code

``` javascript
var Vaulted = require('vaulted');

var vault = new Vaulted({
    vault_host: "myVaultHost",
    no_global_token: true
});

vault.prepare()
.then(function() {
    return vault.init()
})
.then(function(data) {
    console.log(data);
})
```

does not return _token_ and _keys_ as documented. It appears that data is actually an instance of vault, and the token property is not set

![image](https://cloud.githubusercontent.com/assets/929523/12267806/c593dd50-b941-11e5-9cdb-856a823c7b7f.png)

**Comment by kenjones-cisco** [comment]
That is based on the latest master not the latest releases version.

You are running a version other than master as the `keys` attribute was removed as well as the need to use the `no_global_token` (it was removed as well).

**Comment by jmls** [comment]
meh. will pull and retry ;) thanks.

**Comment by jmls** [comment]
perfect - working - thanks again.
