### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#73]
Based on the changes (as noted in the ChangeLog), I'm not sure if we bump to v2.2 or v3.0

All planned tasks and issues are resolved so the release is ready.
- [x] Determine next version
- [x] Set version in package.json
- [x] Update CHANGELOG.md to reference new version with new section for new changes
- [x] Tag project with version
- [x] Create Github Release
- [x] Publish new version to NPM

**Comment by chiefy** [comment]
@kenjones-cisco :+1: will take a look ASAP, have a bit of a stomach bug at the moment.

**Comment by kenjones-cisco** [comment]
@chiefy  After merging #74, ready to take a look and publish the next version?

**Comment by chiefy** [comment]
Since there's breaking changes, let's bump to `3.0.0`?

**Comment by kenjones-cisco** [comment]
Sounds good, :+1:

**Comment by kenjones-cisco** [comment]
All tasks are complete except for publishing to NPM, I put the date as tomorrow (in ChangeLog).

@chiefy Push when you get a chance to NPM.

**Comment by chiefy** [comment]
:+1: will get to it later tonight, thanks!
