### ISSUE TITLE
Setup Github-Pages to publish documentation

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#74]
https://pages.github.com/
- [x] Create gh-pages branch
- [x] Add gulp task deploy-docs that uses html task as pre-task
- [x] Drop docs/
- [x] Drop previous gulp task and dependencies
- [x] Add reference to new docs page
- [x] Merge branch task/html-docs
- [x] Update project description line to include link to docs page

**Comment by kenjones-cisco** [comment]
http://charliegleason.com/articles/deploying-to-github-pages-with-gulp

**Comment by kenjones-cisco** [comment]
Adds the generating HTML documentation for publication to gh-pages
https://github.com/chiefy/vaulted/tree/task/html-docs

**Comment by kenjones-cisco** [comment]
@chiefy Take a look, and try generating output to see what it could look like, and provide thoughts.

**Comment by chiefy** [comment]
Gotta take a look, but there's some weird css stuff going on [here](http://chiefy.github.io/vaulted/module-backend_pki.html)

**Comment by kenjones-cisco** [comment]
That is because of some inconsistencies in how I documented the parameters.

In some places it looks like this:

```
 * @param {Object} options - object of options to send to API request
 * @param {string} options.id - role name
 * @param {Object} options.body - holds the attributes passed as inputs
```

And others like this:

```
 * @param {Object} options.body - holds the attributes passed as inputs
 * @param {string} options.body.address - address of the Consul instance, provided as host:port
 * @param {string} options.body.token - Consul ACL token to use; must be a management type token
```

If instead of including the line:

```
 * @param {Object} options - object of options to send to API request
```

And just start with the first attribute of options, then the formatting would probably look much better.

**Comment by kenjones-cisco** [comment]
After scanning through the pages, overall I think it looks great, but there are some opportunities to improve the documentation so that it formats well everywhere. And many of the "global" stuff is properly documented so that it shows up in the right location.

Instead of putting all the content into README which will also gets replicated to NPM. maybe there is another file we could use to provide the same information where README is a summary with links to the actual documentation page.

Also, then we can decide whether to deprecate the docs/ directory and generating documentation as markdown.

**Comment by kenjones-cisco** [comment]
Updated the docs within the branch, and then pushed the latest generated documentation to gh-pages.

Looks better. @chiefy thoughts?

**Comment by kenjones-cisco** [comment]
@chiefy ready to merge?

**Comment by chiefy** [comment]
merged!

**Comment by kenjones-cisco** [comment]
:+1:
