### ISSUE TITLE
Tracking: parity with current secret backends

### ISSUE THREAD

**Issue by chiefy** [chiefy/vaulted#84]
- [ ] AWS
- [ ] Cassandra
- [x] Consul
- [x] Cubbyhole
- [x] Generic
- [ ] MSSQL
- [ ] MySQL
- [x] PKI (Certs)
- [ ] PostgreSQL
- [ ] ssh
- [ ] Transit
- [ ] RabbitMQ
- [ ] Custom

**Comment by dgreene-r7** [comment]
Is this issue out of date? I noticed you've implemented the pki and cubbyhole backends already.

**Comment by chiefy** [comment]
@dgreene-r7 yeah, thanks - I meant to check those off as @kenjones-cisco took care of them a while ago.
