### ISSUE TITLE
Inconsistent between throw and Promise.reject usage

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#9]
vaulted.validateEndpoint throws Errors, but the usage of this method is as a wrapper around many of the exposed APIs to make sure that the Vault has been initialized and unsealed. Each of those APIs return a promise that is resolved or rejected. And in some cases return a rejected promise if the provided inputs are not correct.

Need to provide consistency such that a call to any of the APIs only results in a promise that is either resolved or rejected and not with thrown Errors. The throw Errors should be maintained as part of creating an instance of Vault.

**Comment by kenjones-cisco** [comment]
Found solution to the issue:

Instead of:

``` javascript
Vaulted.getMounts =function getMounts() {
  return this.getMountsEndpoint()
    .get({
      headers: this.headers
    })
    .promise()
    .bind(this)
    .then(function gotMounts(mounts) {
      this.mounts = mounts;
      return this.mounts;
    });
};
```

Wrap with:

``` javascript
Vaulted.getMounts = Promise.method(function getMounts() {
  return this.getMountsEndpoint()
    .get({
      headers: this.headers
    })
    .promise()
    .bind(this)
    .then(function gotMounts(mounts) {
      this.mounts = mounts;
      return this.mounts;
    });
});
```

`Promise.method` will handle converting any thrown exceptions into rejections so that all calls to the different APIs will be completely promised based.

Example test case to validate:

``` javascript
    it('should reject with an Error if not initialized or unsealed', function () {
      var newVault = new Vault({});
      return newVault.getMounts().should.be.rejectedWith(/Vault has not been initialized/);
    });
```

Changes and tests are already in progress.

**Comment by kenjones-cisco** [comment]
resolved within branch `chore/test-and-docs` but will be handled once the consul changes are or a subset of work there is applied to enable these changes.

The branch will need some clean up to avoid branch merge.

**Comment by chiefy** [comment]
Hey @kenjones-cisco I think I want to avoid using `Promise.method` and rather `.catch` as it subscribes more to the promise pattern. I did some refactoring tonight in my own branch. The tests aren't passing yet, but I think you can take a look. I'd like to avoid getting into "pyramid" promise chains, and make sure things are easily grokked. Thanks again for all your work!

**Comment by kenjones-cisco** [comment]
Unfortunately the `.catch` is not going to work in this scenario because the exception happens prior to any promise execution. The call to `validateEndpoint` or `api.getEndpoint` are synchronous calls that return the initial promise that starts the chain. Since that is where the exceptions are being thrown the catch will not handle the exceptions coming from those synchronous methods.

That is why I went the `Promise.method` route since changing the above methods to be async as well didn't seem like a good idea since their only purpose is to lookup the registered endpoint in a hash and return a properly constructed request-promise to execute.

```
Returns a new function that wraps the given function fn. The new function will always return a promise that is fulfilled with the original functions return values or rejected with thrown exceptions from the original function.
```

Based on the above statement from the bluebird documentation it just provides a simple wrapper around the methods to avoid having to put try/catch -> reject inside each and every method such that a simple promise is always returned.

**Comment by kenjones-cisco** [comment]
I applied the changes from your branch to `chore/test-and-docs` along with updates to resolve some of the test issues.

The `Promise.method` remained and reverted the change for `internal.backup` (comments in-line on your branch).

The refactoring and the updates to simplify the promise chaining were great! The overall code coverage is +98% now!

**Comment by chiefy** [comment]
@kenjones-cisco ah, OK. Sorry, I am fighting a bad cold and was trying to program through it last night. But I see what you're saying now re: `Promise.method` usage. :+1:

**Comment by kenjones-cisco** [comment]
Hope you get feeling better soon!

**Comment by kenjones-cisco** [comment]
PR #11 should resolve this.
